### ISSUE TITLE
feat(Users):Order user list by lastName ascending when choosing Community > People in the sidebar

### ISSUE THREAD

**Issue by irag** [BillionOysterProject/Digital-Platform#593]
This is an enhancement.

When choosing Community > People in the sidebar, the returned user list is not sorted.  This makes it difficult to find people.  I suggest ordering the list by lastName.

My BOP username is Ira Gershenhorn.

In `\modules\profiles\client\views\user\list-users.client.view.html`
Line 75
Replace:
`<tr ng-repeat="user in users" ng-click="openViewUserModal(user)">`
with:
`<tr ng-repeat="user in users | orderBy 'lastName'" ng-click="openViewUserModal(user)">`

Disclaimer:  I cannot tell if this code is used anywhere else and if that anywhere else relies on the absence of ordering.

If I were able to, I would tag this issue as enhancement and help wanted.

**Comment by haflanagan** [comment]
@irag Definitely agree this would be a great enhancement and thank you so much for sending along the code! I'm going to play around with it in our dev environment to see if anything breaks (but I don't see why it would).  I'll probably work on it next week.  I'll let you know how it goes!

**Comment by haflanagan** [comment]
We ended up not addressing this issue with the current version of the platform but @irag we will make the user list sortable as per your suggestion on the rewrite.  Thanks for the feedback!
