### ISSUE TITLE
On Data->Download screen, hitting download doesn't always yield the export-expeditions.csv save or open choice popup.

### ISSUE THREAD

**Issue by irag** [BillionOysterProject/Digital-Platform#612]
On https://platform.bop.nyc/expeditions/data, using Firefox.  I just tried it in Chrome.  So much better - not really - faster, but still get no return.  A completely different presentation.  I think you just need a note that one should use Chrome and avoid Firefox at all costs.

I set a filter of Start Date = 2018-06-01 to End Date= 2018-07-01.  I hit ENTER and got the swirly thing on top. It disappeared.  I selected all parameters.  I hit Download.  Again I got the swirly thing.  Then nothing.  Once when I set a filter of 2018-07-01 and 2018-09-01 I got the export-expeditions.csv popup but not consistently.

With the Start Date = 2018-06-01 to End Date= 2018-07-01, I get the following information:
Your current filters result in the following 10 expeditions: 3rd Expedition - Year 2 , 2018-0609 Demo for Summer on the Hudson , First Expedition Station 18 , First Expedition Station 190 , First Expedition Station 192 , First Expedition Station 189 , First Expedition Station 191 , Science Barge Summer 2018 #1 , Cage 188 Second Observation , Science Barge Summer 2018 #2 , 

So it is finding expeditions.
I tried unsetting a data selection and resetting.  I got the swirly thing

**Comment by haflanagan** [comment]
Yes, unfortunately (as you and I emailed about just now) this is a known issue and it is an incredibly frustrating one.  It will be addressed by the rewrite of the platform which we're hoping to release as a beta towards the end of September!  I really appreciate everyone sticking with the platform through this!

**Comment by haflanagan** [comment]
I'm going to close this issue since it will be addressed with the rewrite but I promise I have taken this fully into consideration!
